import React from 'react';
import type {IconRegistry} from '@astryxdesign/core/Icon';
import {
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Check,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Calendar,
  Clock,
  ExternalLink,
  Menu,
  MoreHorizontal,
  Search,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  Filter,
  EyeOff,
  Columns,
  Copy,
  CheckCheck,
  Wrench,
  PanelLeftClose,
  PanelLeftOpen,
} from 'lucide-react';

export const scholarIconRegistry: IconRegistry = {
  close: X,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  check: Check,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'alert-triangle': AlertTriangle,
  info: Info,
  calendar: Calendar,
  clock: Clock,
  'external-link': ExternalLink,
  menu: Menu,
  'more-horizontal': MoreHorizontal,
  search: Search,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-up-down': ArrowUpDown,
  filter: Filter,
  'eye-off': EyeOff,
  columns: Columns,
  copy: Copy,
  'check-check': CheckCheck,
  wrench: Wrench,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
};
